# Generated by Django 4.2.4 on 2023-09-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccounttoken',
            name='date',
            field=models.DateField(null=True, verbose_name='Gerado em'),
        ),
    ]
