# Generated by Django 4.2.4 on 2023-09-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clientaccounttoken_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaccounttoken',
            name='token',
            field=models.CharField(max_length=800, verbose_name='Token'),
        ),
    ]
