# Generated by Django 4.2.4 on 2023-10-01 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_clientaccounttoken_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientaccounttoken',
            name='token',
        ),
        migrations.AddField(
            model_name='clientaccounttoken',
            name='access_token',
            field=models.CharField(blank=True, max_length=300, verbose_name='Access Token'),
        ),
        migrations.AddField(
            model_name='clientaccounttoken',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=300, verbose_name='Refresh Token'),
        ),
        migrations.AlterField(
            model_name='clientaccounttoken',
            name='date',
            field=models.DateField(null=True, verbose_name='Criado em'),
        ),
    ]
