# Generated by Django 4.2.4 on 2023-08-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pai', models.CharField(blank=True, max_length=254, verbose_name='Nome do pai')),
                ('mae', models.CharField(max_length=254, verbose_name='Nome da mãe')),
                ('nome', models.CharField(max_length=254, verbose_name='Nome completo')),
                ('sexo', models.CharField(max_length=10, verbose_name='Sexo')),
                ('nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('rg', models.CharField(max_length=9, verbose_name='Identidade')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('telefone', models.CharField(max_length=14, verbose_name='Telefone')),
                ('endereco', models.CharField(max_length=254, verbose_name='Endereço')),
                ('cargo', models.CharField(max_length=20, verbose_name='Cargo')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Salário R$')),
                ('admissao', models.DateField(blank=True, null=True, verbose_name='Admissão')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
    ]
